### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by f4depo** [brpaz/ulauncher-cloudflare#1]
I give this error after enter my api...

Message: 'com.github.brpaz.ulauncher-cloudflare'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-cloudflare'

```

**Comment by GregaVrbancic** [comment]
Try to install plugin dependency manually with ```pip3 install cloudflare```

**Comment by brpaz** [comment]
> Try to install plugin dependency manually with `pip3 install cloudflare`

That´s it. It is explicity in the README file. Closing.
